### ISSUE TITLE
Case studies disappear

### ISSUE THREAD

**Issue by johnfoderaro** [plloyd11/craftand#21]
If a 404 error is encountered and the back button is pressed, case studies disappear.

**Comment by plloyd11** [comment]
Anytime you navigate away from the page and come back, the most recent shown study disappears

**Comment by johnfoderaro** [comment]
Closing for now, issue resolved in a prior commit that was merged to master: https://github.com/plloyd11/craftand/commit/87f98e171fcf577904818fc3a231a1537630b3cb
