### ISSUE TITLE
Case Studies - Carousel Functionality

### ISSUE THREAD

**Issue by plloyd11** [plloyd11/craftand#34]
Create three fields for Carousels: Photo, Header, Body and let a user create as many carousel items as they want

**Comment by johnfoderaro** [comment]
I pushed up a branch with what I thought would be how we would approach this, but it breaks the carousel functionality when there is a loop within the `agile` component. That library has many issues on the subject (few opened, most closed) within its GitHub repo, but nothing I tried solved the problem. Hopefully its something simple/obvious I'm over looking.

**Comment by johnfoderaro** [comment]
Closed by https://github.com/plloyd11/craftand/pull/42
