### ISSUE TITLE
Case Studies - Duplicate URL Slug

### ISSUE THREAD

**Issue by plloyd11** [plloyd11/craftand#36]
Check to make sure a user can't create two different case studies with the same URL

**Comment by johnfoderaro** [comment]
Looks like there isn't much we can do which would be worth the use of time to prevent this. If duplicate slugs exist, it will only ever create a node in GraphQL for one of them, so it would definitely break things if they do this.

The best bet is to just add some helper text in Forestry and explain that this is something they need to be mindful of. Gonna close for now.
